
spring:
  datasource:
    url: jdbc:mysql://${DATABASE_URL}
    username: root
    password: hieu
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
#  mail:
#    username: danghieu14th@gmail.com
#    password:
#    host: smtp.gmail.com
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
  liquibase:
    change-log: classpath:changelog-master.xml

  main:
    allow-bean-definition-overriding: true
logging:
  config: classpath:log4j2-local.xml
  level:
    root: info
log4j:
  logger:
    org:
      apache:
        http: DEBUG

TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}

kafka-host: kafka-local:9092